### PR TITLE
Exit with status code 1 on error

### PR DESCRIPTION
**Pull request by chrsm**
This addresses the issue my colleague reported [here](https://github.com/leighmcculloch/vangen/issues/14#issue-1287834987).

I *think* I caught all the appropriate cases (rather than just this specific one). Not sure if this is inline with how you'd prefer it to be implemented, happy to make adjustments.

### CODE REVIEW

**Review by leighmcculloch — COMMENTED** [review]
Thanks for opening a fix for this and for addressing it for all the other error cases that weren't being captured in the exit status.

I'd be inclined to return the errors from the function, then capture the error in the main function, so that the main function is small and all other code is just passing errors. 

What do you think?

**Comment by chrsm** [comment]
Hi @leighmcculloch no problem!

Since these changes are in `main`, are you suggesting some refactoring to move the indexing/writing into separate functions that just return errors? I can handle that.

**Comment by leighmcculloch** [comment]
Yup. The refactor is quite minor, just renaming `main` to something else like `run` that returns an error, and in main if error exit 1 as you did in the helper function.

**Comment by chrsm** [comment]
@leighmcculloch updated, let me know what you think! Sorry for the delay, I have been 😷

**Comment by leighmcculloch** [comment]
@chrsm Looks great!!! Thanks!!!

**Pull request merged**
